<?php

namespace M2I\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function myLastArticleList()
    {
        $qb = $this->createQueryBuilder('a');

        $qb->orderBy('a.createDate', 'DESC');
        $qb->setmaxResults(50); // Les 50 derniers articles

        return $qb->getQuery()->getResult();
    }
}
