# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        M2I\UserBundle\Entity\User: plaintext
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
    providers:
        main:
            entity:
                class:      M2I\UserBundle\Entity\User
                property:   username
        #in_memory:
        #    memory:
        #        users:
        #            user:  { password: userpass, roles [ 'ROLE_USER' ] }
        #            admin: { password: adminpass, roles [ 'ROLE_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path:   login
                check_path:   login_check
            logout:
                path:         logout
                target:       /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/article, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
